name: flake8

on: [pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: flake8
        uses: py-actions/flake8@v2
